version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build: .
    ports: 
     - 8080:8080
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:admin@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
